#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

conky -b -d -c ~/.config/conky/conkyTime
conky -b -d -c ~/.config/conky/conkyrc

# PyWal sourcing the colors
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DisplayPort-2 -d I II III IV V
bspc monitor DisplayPort-3 -d VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12
bspc config top_padding		30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bspc rule -a Alacritty desktop='^1'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Thunar desktop='^4'
bspc rule -a discord desktop='^5'

bspc rule -a Spotify desktop='^7'
bspc rule -a "VirtualBox Manager" desktop='^8'
bspc rule -a  corectrl desktop='^0'

bspc rule -a Screenkey manage=off

