#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc monitor DisplayPort-1 -d I II III IV V
bspc monitor DisplayPort-2 -d VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12
bspc config top_padding		30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a brave-browser desktop='^2'
bspc rule -a Alacritty desktop='^1'
bspc rule -a spotify desktop='^7'
bspc rule -a Screenkey manage=off
